apiVersion: apps/v1
kind: Deployment
metadata:
  name: heydev-www
spec:
  replicas: 1
  selector:
    matchLabels:
      name: heydev-www
  template:
    metadata:
      labels:
        name: heydev-www
    spec:
      containers:
        - image: heydevregistry.azurecr.io/www
          imagePullPolicy: Always
          name: heydev-www
          envFrom:
            - secretRef:
                name: 'config-heydev-www'
---
apiVersion: v1
kind: Service
metadata:
  name: heydev-www
  labels:
    name: heydev-www
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: heydev-www
---
